version: '3.8'
x-backend:
  &backend
  build:
    dockerfile: ./.docker/Dockerfile
    context: .
    args:
      RUBY_VERSION: '2.7.2'
      PG_MAJOR: '10'
      BUNDLER_VERSION: '2.2.15'
      NODE_MAJOR: '14'
      YARN_VERSION: '1.22.5'
      NODE_ENV: production
      RAILS_ENV: production
  env_file: .env
services:
  app:
    <<: *backend
    stdin_open: true
    tty: true
    container_name: app_helphub
    ports:
      - "${DOCKER_PORT}:3000"
    command: ./start.sh
    volumes:
      - ./public:/app/public
      - '../storage:/app/storage'
    depends_on:
      - postgres
      - redis
  sidekiq:
    <<: *backend
    container_name: sidekiq_helphub
    command: ./start_sidekiq.sh
    depends_on:
      - app
      - postgres
      - redis

  postgres:
    container_name: db_helphub
    image: skywidesoft/postgres-hstore-postgis
    volumes:
      - ${DATA_SAVE_PATH}:/var/lib/postgresql/data
  redis:
    container_name: redis_helphub
    image: redis:6.0.9-alpine
    volumes:
      - redis:/data

volumes:
  redis:
