version: '3.8'
x-backend: &backend
  build:
    dockerfile: ./.dockerDev/Dockerfile
    context: .
    args:
      RUBY_VERSION: '2.7.2'
      PG_MAJOR: '10'
      BUNDLER_VERSION: '2.2.15'
      NODE_MAJOR: '14'
      YARN_VERSION: '1.22.5'
  env_file: .env
  stdin_open: true
  tty: true
  depends_on:
    - postgres
    - redis
  volumes:
    - ~/.ssh:/root/.ssh
    - .:/app:cached
    - helphub-packs:/app/public/packs
    - helphub-cache:/app/tmp/cache
    - helphub-bundle:/usr/local/bundle
    - helphub-node_modules:/app/node_modules
    - storage:/app/storage
services:
  app:
    <<: *backend
    container_name: app_helphub
    ports:
      - "${DOCKER_PORT}:3000"
    command: bundle exec rails s -p 3000 -b 0.0.0.0

  sidekiq:
    <<: *backend
    container_name: sidekiq_helphub
    command: bundle exec sidekiq -C config/sidekiq.yml

  postgres:
    container_name: db_helphub
    image: skywidesoft/postgres-hstore-postgis
    volumes:
      - ${DATA_SAVE_PATH}:/var/lib/postgresql/data

  redis:
    image: redis:6.2.5-alpine
    volumes:
      - redis:/data

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

volumes:
  postgres:
  redis:
  helphub-cache:
  helphub-bundle:
  helphub-node_modules:
  helphub-packs:
  storage:
