version: '3.4'
services:
  app:
    environment:
      - RAILS_ENV=development
      - RUBYOPT=-W0
      - LANG=en_US.UTF-8
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: ./start.sh
  postgres:
    image: skywidesoft/postgres-hstore-postgis
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - 5432:5432
  redis:
    image: redis:5.0.4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres:
  redis:  