version: '3.4'
x-backend:
  &backend
  build: .
  environment:
    - RAILS_ENV=development
    - RUBYOPT=-W0
    - LANG=en_US.UTF-8
    - REDIS_URL=redis://redis:6379
    - BUNDLE_PATH=/bundle/vendor
  volumes:
    - .:/app
    - bundle_path:/bundle
  depends_on:
    - postgres
    - redis
services:
  app:
    <<: *backend
    ports:
      - "3000:3000"
    command: ./start.sh 
  sidekiq:
    <<: *backend
    command: ./start_sidekiq.sh
  postgres:
    image: skywidesoft/postgres-hstore-postgis
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - 5432:5432
  redis:
    image: redis:5.0.4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres:
  redis:
  bundle_path: