version: '3.4'
services:
  app:
    environment:
      - RAILS_ENV=development
      - RUBYOPT=-W0
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.12
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: