version: '3.4'
x-backend:
  &backend
  build:
    dockerfile: ./.docker/Dockerfile
    context: .
    args:
      RUBY_VERSION: '2.7.0'
      PG_MAJOR: '10'
      BUNDLER_VERSION: '2.1.4'
      NODE_MAJOR: '14'
      YARN_VERSION: '1.22.5'
      NODE_ENV: production
      RAILS_ENV: production
  env_file: .env
  volumes:
    - ~/.ssh:/root/.ssh
    - .:/app
    - "${REPORTS_PATH}:/reports"
services:
  app:
    <<: *backend
    container_name: app_helphub
    ports:
      - "${DOCKER_PORT}:3000"
    command: ./start.sh
    depends_on:
      - postgres
      - redis
  sidekiq:
    <<: *backend
    container_name: sidekiq_helphub
    command: ./start_sidekiq.sh
    depends_on:
      - app
      - postgres
      - redis

  postgres:
    container_name: db_helphub
    image: skywidesoft/postgres-hstore-postgis
    volumes:
      - ${DATA_SAVE_PATH}:/var/lib/postgresql/data
  redis:
    image: redis:5.0.4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 10.10.0.0/16

volumes:
  postgres:
  redis:
