default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  timeout: 5000
  host: postgres
  username: postgres
  password:

development:
  <<: *default
  url: app_development

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', 'app_test') %>

production:
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  timeout: 5000
  url: <%= ENV.fetch('DATABASE_URL', 'app_production').sub(/^postgres/, "postgis") %>

staging:
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  timeout: 5000
  url: <%= ENV.fetch('DATABASE_URL', 'app_production').sub(/^postgres/, "postgis") %>

