name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  push:
    if: github.event_name == 'push'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Start deploying to the production server
        uses: appleboy/ssh-action@master
        with:
          host: 18.198.123.166
          username: helphub
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if [ ! -d production ]; then
              mkdir production
            fi
            cd production
            ls -la
            if [ ! -d helphub ]; then
              git clone git@github.com:helphubteam/helphub.git
            fi
            cd helphub
            git checkout master && git pull
            cp ~/.production.env ~/production/helphub/.env
            docker-compose -f ./docker-compose.prod.yml up -d --build
